-- ============================================================================
-- TTS audio storage bucket (Korean)
-- ============================================================================
-- Persisted audio files generated by the Gemini TTS integration. File name
-- is `{sha256(languageCode + voice + slow + text)}.wav`. Bucket is public-read
-- so the browser can load the audio directly; writes go through the service role.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tts-audio',
  'tts-audio',
  true,
  10485760, -- 10 MB per file
  array['audio/wav', 'audio/mpeg', 'audio/mp3']
)
on conflict (id) do update
  set public              = excluded.public,
      file_size_limit     = excluded.file_size_limit,
      allowed_mime_types  = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public read tts-audio'
  ) then
    create policy "Public read tts-audio"
      on storage.objects for select
      using (bucket_id = 'tts-audio');
  end if;
end
$$;
